import type { Metadata } from 'next'

import '@/app/ui/global.css'

// 主要字體
import { inter } from '@/app/ui/fonts'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    keywords: '關鍵字1,關鍵字2,關鍵字3',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}
